# Generated by Django 2.2.6 on 2020-07-09 13:31

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lekcije', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lekcije',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=300)),
                ('fajl', models.FileField(upload_to='lekcije', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'ppt', 'pptx', 'jpg'])])),
                ('predmet', models.CharField(choices=[('Matematika', 'Matematika'), ('Fizika', 'Fizika'), ('Srpski jezik i književnost', 'Srpski jezik i književnost'), ('Srpski kao nematernji jezik', 'Srpski kao nematernji'), ('Bosanski jezik i književnost', 'Bosanski jezik i književnost'), ('Engleski jezik', 'Engleski jezik'), ('Nemački jezik', 'Nemački jezik'), ('Francuski jezik', 'Francuski jezik'), ('Latinski jezik', 'Latinski jezik'), ('Istorija', 'Istorija'), ('Geografija', 'Geografija'), ('Biologija', 'Biologija'), ('Hemija', 'Hemija'), ('Računarstvo i informatika', 'Računarstvo i informatika'), ('Muzička kultura', 'Muzička kultura'), ('Likovna kultura', 'Likovna kultura'), ('Fizičko vaspitanje', 'Fizičko vaspitanje'), ('Građansko vaspitanje', 'Građansko vaspitanje'), ('Islamska veronauka', 'Islamska veronauka'), ('Pravoslavna veronauka', 'Pravoslavna veronauka'), ('Jezik medija i kultura', 'Jezik medija i kultura'), ('Primenjene nauke', 'Primenjene nauke'), ('Umetnost i dizajn', 'Umetnost i dizajn'), ('Zdravlje i sport', 'Zdravlje i sport'), ('Psihologija', 'Psihologija'), ('Filozofija', 'Filozofija'), ('Sociologija', 'Sociologija'), ('Ustav i prava građana', 'Ustav i prava građana')], max_length=40)),
                ('godina', models.CharField(choices=[('Prva godina', 'Prva godina'), ('Druga godina', 'Druga godina'), ('Treća godina', 'Treća godina'), ('Četvrta godina', 'Četvrta godina')], max_length=40)),
                ('autor', models.CharField(max_length=40)),
                ('vreme_posta', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Započni lekciju(ili dodaj sliku)',
                'ordering': ['predmet', 'autor'],
            },
        ),
        migrations.CreateModel(
            name='Ucenik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=300)),
                ('prezime', models.CharField(max_length=300)),
                ('maticni_broj', models.BigIntegerField(unique=True)),
                ('smer', models.CharField(choices=[('Prirodno matematički smer', 'Prirodno matematički smer'), ('Društveno jezički smer', 'Društveno jezički smer'), ('Opšti smer', 'Opšti smer'), ('IT-smer', 'IT-smer'), ('Odeljenje za  učenike nadarene za sport', 'Odeljenje za  učenike nadarene za sport')], max_length=40)),
                ('jezik_na_kojem_se_odvija_nastava', models.CharField(choices=[('Srpski jezik ', 'Srpski jezik '), ('Bosanski jezik ', 'Bosanski jezik ')], max_length=40)),
                ('prvi_strani_jezik', models.CharField(choices=[('Engleski jezik', 'Engleski jezik'), ('Nemački jezik', 'Nemački jezik'), ('Francuski jezik', 'Francuski jezik')], max_length=40)),
                ('drugi_strani_jezik', models.CharField(choices=[('Engleski jezik', 'Engleski jezik'), ('Nemački jezik', 'Nemački jezik'), ('Francuski jezik', 'Francuski jezik')], max_length=40)),
                ('izborni_predmet', models.CharField(choices=[('Islamska veronauka', 'Islamska veronauka'), ('Pravoslavna veronauka', 'Pravoslavna veronauka'), ('Građansko vaspitanje', 'Građansko vaspitanje')], max_length=40)),
                ('prvi_izborni_program', models.CharField(blank=True, choices=[('Jezik medija i kultura', 'Jezik medija i kultura'), ('Primenjene nauke', 'Primenjene nauke'), ('Umetnost i dizajn', 'Umetnost i dizajn'), ('Zdravlje i sport', 'Zdravlje i sport')], max_length=300, null=True)),
                ('drugi_izborni_program', models.CharField(blank=True, choices=[('Jezik medija i kultura', 'Jezik medija i kultura'), ('Primenjene nauke', 'Primenjene nauke'), ('Umetnost i dizajn', 'Umetnost i dizajn'), ('Zdravlje i sport', 'Zdravlje i sport')], max_length=300, null=True)),
                ('odeljenje', models.CharField(blank=True, choices=[('I-1', 'I-1'), ('I-2', 'I-2'), ('I-3', 'I-3'), ('I-4', 'I-4'), ('I-5', 'I-5'), ('I-6', 'I-6'), ('I-7', 'I-7'), ('I-8', 'I-8'), ('I-9', 'I-9'), ('I-10', 'I-10'), ('I-11', 'I-11'), ('I-12', 'I-12')], max_length=300, null=True)),
            ],
            options={
                'verbose_name_plural': 'Prijava ucenika za prvi razred',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=300)),
                ('nalepi_Youtube_link', models.CharField(max_length=100)),
                ('predmet', models.CharField(choices=[('Matematika', 'Matematika'), ('Fizika', 'Fizika'), ('Srpski jezik i književnost', 'Srpski jezik i književnost'), ('Srpski kao nematernji jezik', 'Srpski kao nematernji'), ('Bosanski jezik i književnost', 'Bosanski jezik i književnost'), ('Engleski jezik', 'Engleski jezik'), ('Nemački jezik', 'Nemački jezik'), ('Francuski jezik', 'Francuski jezik'), ('Latinski jezik', 'Latinski jezik'), ('Istorija', 'Istorija'), ('Geografija', 'Geografija'), ('Biologija', 'Biologija'), ('Hemija', 'Hemija'), ('Računarstvo i informatika', 'Računarstvo i informatika'), ('Muzička kultura', 'Muzička kultura'), ('Likovna kultura', 'Likovna kultura'), ('Fizičko vaspitanje', 'Fizičko vaspitanje'), ('Građansko vaspitanje', 'Građansko vaspitanje'), ('Islamska veronauka', 'Islamska veronauka'), ('Pravoslavna veronauka', 'Pravoslavna veronauka'), ('Jezik medija i kultura', 'Jezik medija i kultura'), ('Primenjene nauke', 'Primenjene nauke'), ('Umetnost i dizajn', 'Umetnost i dizajn'), ('Zdravlje i sport', 'Zdravlje i sport'), ('Psihologija', 'Psihologija'), ('Filozofija', 'Filozofija'), ('Sociologija', 'Sociologija'), ('Ustav i prava građana', 'Ustav i prava građana')], max_length=40)),
                ('godina', models.CharField(choices=[('Prva godina', 'Prva godina'), ('Druga godina', 'Druga godina'), ('Treća godina', 'Treća godina'), ('Četvrta godina', 'Četvrta godina')], max_length=40)),
                ('autor', models.CharField(max_length=40)),
                ('vreme_posta', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Dodaj video(ako želiš)',
                'ordering': ['autor'],
            },
        ),
    ]
