# Generated by Django 2.2.6 on 2020-03-28 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lekcije', '0002_auto_20200322_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lekcije',
            name='fajl',
            field=models.FileField(upload_to='lekcije', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'ppt', 'pptx', 'jpg'])]),
        ),
    ]
