# Generated by Django 2.2.6 on 2020-08-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lekcije', '0002_lekcije_ucenik_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='IzborNastave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_prezime_ucenika', models.CharField(max_length=300)),
                ('odeljenje', models.CharField(choices=[('I-1', 'I-1'), ('I-2', 'I-2'), ('I-3', 'I-3'), ('I-4', 'I-4'), ('I-5', 'I-5'), ('I-6', 'I-6'), ('I-7', 'I-7'), ('I-8', 'I-8'), ('I-9', 'I-9'), ('I-10', 'I-10'), ('I-11', 'I-11'), ('I-12', 'I-12'), ('II-1', 'II-1'), ('II-2', 'II-2'), ('II-3', 'II-3'), ('II-4', 'II-4'), ('II-5', 'II-5'), ('II-6', 'II-6'), ('II-7', 'II-7'), ('II-8', 'II-8'), ('II-9', 'II-9'), ('II-10', 'II-10'), ('II-11', 'II-11'), ('III-1', 'III-1'), ('III-2', 'III-2'), ('III-3', 'III-3'), ('III-4', 'III-4'), ('III-5', 'III-5'), ('III-6', 'III-6'), ('III-7', 'III-7'), ('III-8', 'III-8'), ('III-9', 'III-9'), ('III-10', 'III-10'), ('III-11', 'III-11'), ('IV-1', 'IV-1'), ('IV-2', 'IV-2'), ('IV-3', 'IV-3'), ('IV-4', 'IV-4'), ('IV-5', 'IV-5'), ('IV-6', 'IV-6'), ('IV-7', 'IV-7'), ('IV-8', 'IV-8'), ('IV-9', 'IV-9'), ('IV-10', 'IV-10')], max_length=30)),
                ('izbor', models.CharField(choices=[('Da', 'Da'), ('Ne', 'Ne')], max_length=30)),
                ('ime_prezime_roditelja', models.CharField(max_length=300)),
            ],
        ),
    ]
