# Generated by Django 2.2.6 on 2020-03-28 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lekcije', '0003_auto_20200328_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lekcije',
            options={'ordering': ['autor'], 'verbose_name_plural': 'Započni lekciju(ili dodaj sliku)'},
        ),
    ]
