# Generated by Django 2.2.6 on 2020-09-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lekcije', '0003_izbornastave'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='izbornastave',
            options={'verbose_name_plural': 'Izbor nastave učenika'},
        ),
        migrations.AlterField(
            model_name='izbornastave',
            name='izbor',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='izbornastave',
            unique_together={('ime_prezime_ucenika', 'ime_prezime_roditelja')},
        ),
    ]
