# Generated by Django 2.2.6 on 2020-09-06 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lekcije', '0005_auto_20200906_1618'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='izbornastave',
            unique_together=set(),
        ),
    ]
