# Generated by Django 2.2.6 on 2020-03-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lekcije', '0005_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='nalepi_link',
            new_name='nalepi_Youtube_link',
        ),
    ]
