# Generated by Django 2.2.6 on 2020-04-05 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lekcije', '0006_auto_20200328_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lekcije',
            options={'ordering': ['predmet'], 'verbose_name_plural': 'Započni lekciju(ili dodaj sliku)'},
        ),
    ]
