# Generated by Django 2.2.6 on 2020-09-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lekcije', '0006_auto_20200906_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lekcije',
            name='predmet',
            field=models.CharField(choices=[('Matematika', 'Matematika'), ('Fizika', 'Fizika'), ('Srpski jezik i književnost', 'Srpski jezik i književnost'), ('Srpski kao nematernji jezik', 'Srpski kao nematernji'), ('Bosanski jezik i književnost', 'Bosanski jezik i književnost'), ('Engleski jezik', 'Engleski jezik'), ('Nemački jezik', 'Nemački jezik'), ('Francuski jezik', 'Francuski jezik'), ('Latinski jezik', 'Latinski jezik'), ('Istorija', 'Istorija'), ('Geografija', 'Geografija'), ('Biologija', 'Biologija'), ('Hemija', 'Hemija'), ('Računarstvo i informatika', 'Računarstvo i informatika'), ('Muzička kultura', 'Muzička kultura'), ('Likovna kultura', 'Likovna kultura'), ('Fizičko vaspitanje', 'Fizičko vaspitanje'), ('Građansko vaspitanje', 'Građansko vaspitanje'), ('Islamska veronauka', 'Islamska veronauka'), ('Pravoslavna veronauka', 'Pravoslavna veronauka'), ('Jezik medija i kultura', 'Jezik medija i kultura'), ('Primenjene nauke', 'Primenjene nauke'), ('Umetnost i dizajn', 'Umetnost i dizajn'), ('Zdravlje i sport', 'Zdravlje i sport'), ('Psihologija', 'Psihologija'), ('Filozofija', 'Filozofija'), ('Sociologija', 'Sociologija'), ('Ustav i prava građana', 'Ustav i prava građana'), ('Obrazovanje za održivi razvoj', 'Obrazovanje za održivi razvoj')], max_length=40),
        ),
        migrations.AlterField(
            model_name='video',
            name='predmet',
            field=models.CharField(choices=[('Matematika', 'Matematika'), ('Fizika', 'Fizika'), ('Srpski jezik i književnost', 'Srpski jezik i književnost'), ('Srpski kao nematernji jezik', 'Srpski kao nematernji'), ('Bosanski jezik i književnost', 'Bosanski jezik i književnost'), ('Engleski jezik', 'Engleski jezik'), ('Nemački jezik', 'Nemački jezik'), ('Francuski jezik', 'Francuski jezik'), ('Latinski jezik', 'Latinski jezik'), ('Istorija', 'Istorija'), ('Geografija', 'Geografija'), ('Biologija', 'Biologija'), ('Hemija', 'Hemija'), ('Računarstvo i informatika', 'Računarstvo i informatika'), ('Muzička kultura', 'Muzička kultura'), ('Likovna kultura', 'Likovna kultura'), ('Fizičko vaspitanje', 'Fizičko vaspitanje'), ('Građansko vaspitanje', 'Građansko vaspitanje'), ('Islamska veronauka', 'Islamska veronauka'), ('Pravoslavna veronauka', 'Pravoslavna veronauka'), ('Jezik medija i kultura', 'Jezik medija i kultura'), ('Primenjene nauke', 'Primenjene nauke'), ('Umetnost i dizajn', 'Umetnost i dizajn'), ('Zdravlje i sport', 'Zdravlje i sport'), ('Psihologija', 'Psihologija'), ('Filozofija', 'Filozofija'), ('Sociologija', 'Sociologija'), ('Ustav i prava građana', 'Ustav i prava građana'), ('Obrazovanje za održivi razvoj', 'Obrazovanje za održivi razvoj')], max_length=40),
        ),
    ]
