# Generated by Django 2.2.6 on 2020-07-08 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lekcije', '0007_auto_20200405_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ucenik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=300)),
                ('prezime', models.CharField(max_length=300)),
                ('maticni_broj', models.DecimalField(decimal_places=0, max_digits=13, unique=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('smer', models.CharField(choices=[('Prirodno matematički smer', 'Prirodno matematički smer'), ('Društveno jezički smer', 'Društveno jezički smer'), ('Opšti smer', 'Opšti smer'), ('IT-smer', 'IT-smer'), ('Odeljenje za  učenike nadarene za sport', 'Odeljenje za  učenike nadarene za sport')], max_length=40)),
                ('jezik_na_kojem_se_odvija_nastava', models.CharField(choices=[('Srpski jezik ', 'Srpski jezik '), ('Bosanski jezik ', 'Bosanski jezik ')], max_length=40)),
                ('prvi_strani_jezik', models.CharField(choices=[('Engleski jezik', 'Engleski jezik'), ('Nemački jezik', 'Nemački jezik'), ('Francuski jezik', 'Francuski jezik')], max_length=40)),
                ('drugi_strani_jezik', models.CharField(choices=[('Engleski jezik', 'Engleski jezik'), ('Nemački jezik', 'Nemački jezik'), ('Francuski jezik', 'Francuski jezik')], max_length=40)),
                ('izborni_predmet', models.CharField(choices=[('Islamska veronauka', 'Islamska veronauka'), ('Pravoslavna veronauka', 'Pravoslavna veronauka'), ('Građansko vaspitanje', 'Građansko vaspitanje')], max_length=40)),
                ('prvi_izborni_program', models.CharField(blank=True, choices=[('Jezik medija i kultura', 'Jezik medija i kultura'), ('Primenjene nauke', 'Primenjene nauke'), ('Umetnost i dizajn', 'Umetnost i dizajn'), ('Zdravlje i sport', 'Zdravlje i sport')], max_length=300, null=True)),
                ('drugi_izborni_program', models.CharField(blank=True, choices=[('Jezik medija i kultura', 'Jezik medija i kultura'), ('Primenjene nauke', 'Primenjene nauke'), ('Umetnost i dizajn', 'Umetnost i dizajn'), ('Zdravlje i sport', 'Zdravlje i sport')], max_length=300, null=True)),
                ('odeljenje', models.CharField(blank=True, choices=[('I-1', 'I-1'), ('I-2', 'I-2'), ('I-3', 'I-3'), ('I-4', 'I-4'), ('I-5', 'I-5'), ('I-6', 'I-6'), ('I-7', 'I-7'), ('I-8', 'I-8'), ('I-9', 'I-9'), ('I-10', 'I-10'), ('I-11', 'I-11'), ('I-12', 'I-12')], max_length=300, null=True)),
            ],
            options={
                'verbose_name_plural': 'Prijava ucenika za prvi razred',
            },
        ),
        migrations.AlterModelOptions(
            name='lekcije',
            options={'ordering': ['predmet', 'autor'], 'verbose_name_plural': 'Započni lekciju(ili dodaj sliku)'},
        ),
    ]
