# Generated by Django 2.2.6 on 2020-07-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lekcije', '0008_auto_20200708_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ucenik',
            name='maticni_broj',
            field=models.DecimalField(decimal_places=0, max_digits=13, unique=True),
        ),
    ]
