# Generated by Django 2.2.6 on 2020-03-18 01:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lekcije',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=300)),
                ('fajl', models.FileField(upload_to='lekcije')),
                ('predmet', models.CharField(choices=[('Matematika', 'Matematika'), ('Fizika', 'Fizika'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=40)),
                ('godina', models.CharField(choices=[('Prva godina', 'Prva godina'), ('Druga godina', 'Druga godina'), ('Treća godina', 'Treća godina'), ('Četvrta godina', 'Četvrta godina')], max_length=40)),
                ('autor', models.CharField(max_length=40)),
                ('vreme_posta', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Obaveštenja',
            },
        ),
    ]
